# test_runner.gd — Headless automated test suite for Godot
extends SceneTree

const CoreTests := preload("res://tests/unit/core_tests.gd")
const PersistenceTests := preload("res://tests/unit/persistence_tests.gd")
const HomesteadTests := preload("res://tests/unit/homestead_tests.gd")
const ActorTests := preload("res://tests/unit/actor_tests.gd")
const PresentationTests := preload("res://tests/unit/presentation_tests.gd")
const AutomationTests := preload("res://tests/unit/automation_tests.gd")
const InteriorTests := preload("res://tests/unit/interior_tests.gd")
const BarnTests := preload("res://tests/unit/barn_tests.gd")


func _init() -> void:
	var core = CoreTests.new()
	var persistence = PersistenceTests.new()
	var homestead = HomesteadTests.new()
	var actor = ActorTests.new()
	var presentation = PresentationTests.new()
	var automation = AutomationTests.new()
	var interior = InteriorTests.new()
	var barn = BarnTests.new()

	print(String("=").repeat(60))
	print("TINY FARM - GODOT Automated Test Suite")
	print(String("=").repeat(60))

	core.test_crop_defs()
	core.test_tools()
	core.test_rain_wets_fresh_soil()
	core.test_player()
	core.test_farm()
	core.test_integration()
	core.test_pathfinding()
	core.test_action_router()
	core.test_input_bleed()
	core.test_swipe_chaining()
	core.test_sim_rng()
	core.test_milestones()
	core.test_sim_actions()
	persistence.test_replay()
	persistence.test_save_game()
	persistence.test_interrupted_save_write()
	persistence.test_save_slots()
	persistence.test_save_slot_migration()
	persistence.test_replay_from_save()
	persistence.test_replay_flush()
	homestead.test_crow_scared_verb()
	homestead.test_vignette_multiday()
	homestead.test_gate_lesson_latch_regression()
	homestead.test_takeover_layout()
	homestead.test_phase1_proof()
	homestead.test_autotile()
	homestead.test_autotile_sheet()
	homestead.test_title_summary()
	homestead.test_approach_adjacent()
	homestead.test_approach_ignores_inventory()
	homestead.test_session_trace()
	homestead.test_crow_readiness()
	homestead.test_crow_schedule()
	homestead.test_stateless_schedule_revision()
	homestead.test_crow_raid_trigger()
	homestead.test_crow_raid_waits_for_the_door()
	homestead.test_crow_raid_costs_one_tomato()
	homestead.test_crow_raid_marks_the_plot()
	homestead.test_crow_raid_survives_a_save()
	homestead.test_story_loop_shown_survives_a_save()
	homestead.test_crow_raid_replays()
	homestead.test_daylight()
	homestead.test_energy_repartition()
	homestead.test_q50_clearing_costs()
	homestead.test_clock_digits()
	homestead.test_replay_build_stamp()
	homestead.test_blocked_reason()
	homestead.test_benign_failures()
	homestead.test_seed_selection_trap()
	homestead.test_trace_analyses()
	homestead.test_satisfied_states()
	homestead.test_parcel_generation()
	presentation.test_yard_ground()
	presentation.test_home_layout()
	homestead.test_tool_acquisition()
	homestead.test_lessons_never_point_through_a_door()
	homestead.test_boundary_tap_answers()
	homestead.test_cold_open()
	homestead.test_actor_energy()
	homestead.test_actor_registry()
	homestead.test_takeover_anchoring()
	homestead.test_acorns()
	homestead.test_acorn_pickup()
	homestead.test_economy_teaching()
	homestead.test_offscreen_arrow()
	homestead.test_player_gs_injection()
	homestead.test_pre_m15_saves_load()
	homestead.test_sim_clock()
	actor.test_brains()
	actor.test_movement()
	actor.test_pathfinder_identity()
	actor.test_scent()
	actor.test_sprinkler()
	actor.test_pea()
	actor.test_replay_v2()
	actor.test_hen_replay_from_fresh_save()
	actor.test_ants()
	actor.test_grazers()
	actor.test_songbird()
	actor.test_mole()
	actor.test_worm()
	actor.test_bots()
	presentation.test_cot_halo()
	presentation.test_cot_presentation()
	presentation.test_station_presentation()
	presentation.test_world_tint_presentation()
	presentation.test_crop_presentation()
	presentation.test_zoo()
	presentation.test_rain_on_ripe_soil()
	presentation.test_ground_holds_until_black()
	presentation.test_wetness_soaks_in()
	presentation.test_clear_chips_the_obstacle()
	presentation.test_parcel_introduction_pick()
	automation.test_parcel_scatter()
	automation.test_machines()
	automation.test_mark_one_robot()
	automation.test_machine_economy()
	automation.test_observation()
	automation.test_policy()
	automation.test_learning_robot_day()
	automation.test_workbench_sim()
	automation.test_crate_remembers()
	automation.test_workbench_place()
	automation.test_first_robot_unlocks()
	automation.test_robot_ladder()
	automation.test_robot_story_night()
	automation.test_learning_robot()
	automation.test_worm_practice()
	automation.test_worm_practice_measurement()
	automation.test_wider_view()
	automation.test_starter_brain()
	interior.test_world_pages()
	interior.test_the_door()
	interior.test_the_window()
	interior.test_fencing()
	interior.test_bed_cue_shape()
	interior.test_save_v3_migration()
	interior.test_robot_stall()
	interior.test_stall_floor_is_not_ground()
	interior.test_chicken_coop()
	interior.test_coop_interior()
	interior.test_room_fittings()
	interior.test_spiral_tower_interior()
	interior.test_spiral_tower_pick_up()
	interior.test_senses_stop_at_space_boundary()
	interior.test_robot_usefulness()
	interior.test_one_pouch()
	barn.test_barn_simulation()
	interior.test_carry_cap()
	interior.test_save_v5_migration()
	interior.test_mark_three_assigned_tiles()
	interior.test_refused_brain_action_replays()
	interior.test_workbench_shelf()
	core.test_farm_page_draw_order_merge()
	barn.test_room_edge_styles()

	var areas: Array = [core, persistence, homestead, actor, presentation, automation, interior, barn]
	var pass_count := 0
	var fail_count := 0
	var fail_log: Array[String] = []
	for area in areas:
		pass_count += area.pass_count
		fail_count += area.fail_count
		fail_log.append_array(area.fail_log)

	print("")
	print(String("=").repeat(60))
	print("Results: %d PASSED, %d FAILED" % [pass_count, fail_count])
	if fail_count > 0:
		print("FAILED TESTS:")
		for log_msg in fail_log:
			print("  " + log_msg)
	print(String("=").repeat(60))
	quit(1 if fail_count > 0 else 0)
