# title_screen.gd — boot screen: Continue (with a progress summary) or New Farm.
#
# The Continue card answers "where was I?" before committing to a tap, which
# matters because the game has one save slot. New Farm is deliberately smaller
# and asks for confirmation, since starting one replaces the farm on the next
# sleep (S-7: nothing a pre-reader can tap should destroy progress silently).
extends Control

const CARD_W := 340
const CARD_H := 132

# Alternate takes awaiting a verdict; empty once one is promoted or dropped.
# Generated by tools/gen_sfx.py --alt.
const SFX_CANDIDATES := []

var _has_save := false
var _summary: Dictionary = {}
var _confirm_open := false
var _confirm_layer: Control = null


const DEMO_REPLAY_PATH := "res://assets/demo/demo_replay.json"
var _attract: Node2D = null


func _ready() -> void:
	_start_attract()
	_has_save = FileAccess.file_exists(GameState.save_path)
	if _has_save:
		_summary = _read_summary()
		# A save we cannot parse is not a save we can offer to continue.
		if _summary.is_empty():
			_has_save = false
	_build_ui()


# T-16 (Q-40): the menu sits over a real farm being played. Everything about
# what it plays and how is in `ui/attract_loop.gd`; this only decides whether to.
func _start_attract() -> void:
	var AttractScript = load("res://ui/attract_loop.gd")
	if not AttractScript.ATTRACT_ENABLED:
		return
	# Headless has nothing to render into and no reason to spend the frames.
	if DisplayServer.get_name() == "headless":
		return
	var replay: ReplayLog = AttractScript.choose_replay(GameState.replay_path, DEMO_REPLAY_PATH)
	if replay == null:
		return  # first boot on a fresh install: keep the flat backdrop

	var loop = AttractScript.new()
	loop.name = "AttractLoop"
	# Draw order is tree order, and `_ready` runs this *before* `_build_ui`, so the
	# farm lands after the backdrop and before the menu: backdrop, farm, buttons.
	# It is a Node2D and takes no input, so every tap still reaches the menu above
	# it and tap-anywhere-to-continue still reaches the title screen itself.
	add_child(loop)
	if not loop.begin(replay):
		loop.queue_free()
		return
	_attract = loop

	# The flat backdrop stays as the thing *behind* the farm rather than being
	# deleted — the drifting layer need not cover every pixel — but it darkens,
	# because a bright green rectangle beside a real farm reads as a hole.
	var back := get_node_or_null("ColorRect")
	if back != null:
		back.color = Color(0.13, 0.28, 0.17)

	# One moving thing at a time — the build hash would otherwise sit over a
	# moving farm, and it is a developer's label rather than part of the picture.
	# Restored in _exit_tree: BuildOverlay is an autoload and outlives this scene,
	# so hiding it without putting it back would silently remove it from the game
	# itself, which is the one place it is actually useful.
	_hide_build_overlay(true)


func _build_overlay() -> CanvasLayer:
	return get_tree().root.get_node_or_null("BuildOverlay") as CanvasLayer


func _hide_build_overlay(hidden: bool) -> void:
	var overlay := _build_overlay()
	if overlay != null:
		overlay.visible = not hidden


func _exit_tree() -> void:
	_hide_build_overlay(false)


# Anything that opens a panel over the title pauses the farm behind it: one
# moving thing at a time, which is the same rule the vignette follows.
func _set_attract_paused(value: bool) -> void:
	if _attract != null and is_instance_valid(_attract):
		_attract.paused = value


func _read_summary() -> Dictionary:
	return SaveGame.summarize(SaveGame.load_dict(GameState.save_path))


func _build_ui() -> void:
	var root_box := VBoxContainer.new()
	root_box.set_anchors_preset(Control.PRESET_CENTER)
	root_box.anchor_left = 0.5
	root_box.anchor_top = 0.5
	root_box.anchor_right = 0.5
	root_box.anchor_bottom = 0.5
	root_box.offset_left = -CARD_W / 2.0
	root_box.offset_top = -150
	root_box.offset_right = CARD_W / 2.0
	root_box.offset_bottom = 150
	root_box.add_theme_constant_override("separation", 14)
	root_box.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(root_box)

	var title := Label.new()
	title.text = "Tiny Farm"
	title.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	title.add_theme_font_size_override("font_size", 48)
	title.add_theme_color_override("font_color", Color.WHITE)
	title.add_theme_color_override("font_shadow_color", Color(0, 0, 0, 0.6))
	title.add_theme_constant_override("shadow_offset_x", 2)
	title.add_theme_constant_override("shadow_offset_y", 2)
	title.mouse_filter = Control.MOUSE_FILTER_IGNORE
	root_box.add_child(title)

	if _has_save:
		root_box.add_child(_make_continue_card())
		root_box.add_child(_make_new_farm_button())
	else:
		root_box.add_child(_make_start_button())

	# Deliberately NOT debug-gated: the bundled music is CC BY 4.0 and *requires*
	# an attribution line in the shipped credits (CREDITS.md). Until this existed
	# the game showed credits nowhere, so shipping it publicly would have breached
	# that licence — found on the way to the first release. Small and low-contrast
	# so it does not compete with the one button a pre-reader needs.
	root_box.add_child(_make_credits_button())

	# Debug builds only, so a public release never shows it (the Android export
	# we deploy is --export-debug, so it is present on the test tablet).
	if OS.is_debug_build():
		# One literal row for all three debug doors. They used to stack, and the
		# third one pushed the menu off the bottom of the tablet's screen —
		# reported from the device the night the Zoo landed. Three across at 104px
		# fits the 340px column with the row's two 10px separations to spare.
		# T-37 briefly made it four (a 2x2 grid); the Look Lab's door came back
		# out on 2026-09-02 and it is a single row again — see the note below.
		var debug_row := HBoxContainer.new()
		debug_row.add_theme_constant_override("separation", 10)
		debug_row.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
		debug_row.mouse_filter = Control.MOUSE_FILTER_IGNORE
		root_box.add_child(debug_row)
		# The doors are things to *look at*: the Sound Test plays a sound, the Zoo
		# runs a farm full of entities, the Home (T-37) opens the house. Each one
		# shows you the thing itself when you open it.
		#
		# The Look Lab's door used to sit here and no longer does. It was a panel
		# of buttons, one per draft, and opening it showed nothing — every look it
		# switched between only appears under conditions the title screen does not
		# have (dusk, a crop in the basket, a station never used). The designer's
		# verdict, 2026-09-02: *"The text overfills the buttons, and I don't know
		# what it means... Each step should draw a scenario under specific
		# conditions, and then quiz me."* All three of its questions were ruled on
		# 2026-09-01 and ship as the defaults, so nothing is waiting on it. The
		# switches themselves are unchanged and still in the pause menu, where the
		# farm is what you are looking at when one flips (`ui/menus.gd`), and the
		# registry behind them is still `systems/look_lab.gd`. What replaces the
		# door is a staged scenario, not a menu — Q-86 in `docs/DESIGNER_QUEUE.md`.
		for b in [_make_sound_test_button(), _make_zoo_button(), _make_home_button()]:
			b.custom_minimum_size = Vector2(104, 34)
			debug_row.add_child(b)


func _big_button_style(bg: Color, border: Color) -> StyleBoxFlat:
	var sb := StyleBoxFlat.new()
	sb.bg_color = bg
	sb.border_color = border
	sb.set_border_width_all(3)
	sb.set_corner_radius_all(10)
	sb.content_margin_left = 12
	sb.content_margin_right = 12
	sb.content_margin_top = 10
	sb.content_margin_bottom = 10
	return sb


func _style_button(btn: Button, bg: Color, border: Color, hover: Color) -> void:
	btn.add_theme_stylebox_override("normal", _big_button_style(bg, border))
	btn.add_theme_stylebox_override("hover", _big_button_style(hover, border))
	btn.add_theme_stylebox_override("pressed", _big_button_style(border, border))
	btn.add_theme_stylebox_override("focus", _big_button_style(hover, border))


# The headline action: big target, and it shows the farm it is about to resume.
func _make_continue_card() -> Button:
	var btn := Button.new()
	btn.name = "ContinueButton"
	btn.custom_minimum_size = Vector2(CARD_W, CARD_H)
	_style_button(btn, Color(0.18, 0.42, 0.22), Color(1.0, 0.72, 0.15), Color(0.24, 0.52, 0.28))
	btn.pressed.connect(func(): start_game(true))

	var box := VBoxContainer.new()
	box.set_anchors_preset(Control.PRESET_FULL_RECT)
	box.mouse_filter = Control.MOUSE_FILTER_IGNORE
	box.add_theme_constant_override("separation", 2)
	btn.add_child(box)

	var head := Label.new()
	head.text = "Continue"
	head.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	head.add_theme_font_size_override("font_size", 30)
	head.add_theme_color_override("font_color", Color(1.0, 0.86, 0.45))
	head.mouse_filter = Control.MOUSE_FILTER_IGNORE
	box.add_child(head)

	var day := Label.new()
	day.text = "Day %d" % _summary.get("day", 1)
	day.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	day.add_theme_font_size_override("font_size", 20)
	day.add_theme_color_override("font_color", Color.WHITE)
	day.mouse_filter = Control.MOUSE_FILTER_IGNORE
	box.add_child(day)

	var stats := Label.new()
	stats.text = "%dg     %d shipped     %d crows shooed" % [
		_summary.get("gold", 0), _summary.get("shipped", 0), _summary.get("scared", 0)]
	stats.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	stats.add_theme_font_size_override("font_size", 14)
	stats.add_theme_color_override("font_color", Color(0.86, 0.94, 0.82))
	stats.mouse_filter = Control.MOUSE_FILTER_IGNORE
	box.add_child(stats)

	var progress := Label.new()
	if _summary.get("phase1", false):
		progress.text = "Homestead complete"
		progress.add_theme_color_override("font_color", Color(1.0, 0.86, 0.45))
	else:
		# Same two counters the sim uses for the phase-1 proof (Q-12), so the
		# card shows real progression rather than a decorative number.
		progress.text = "Homestead  %d/%d crops  %d/%d crows" % [
			min(_summary.get("shipped", 0), SimWorld.PHASE1_SHIPPED_TARGET),
			SimWorld.PHASE1_SHIPPED_TARGET,
			min(_summary.get("scared", 0), SimWorld.PHASE1_SCARED_TARGET),
			SimWorld.PHASE1_SCARED_TARGET]
		progress.add_theme_color_override("font_color", Color(0.74, 0.85, 0.70))
	progress.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	progress.add_theme_font_size_override("font_size", 13)
	progress.mouse_filter = Control.MOUSE_FILTER_IGNORE
	box.add_child(progress)

	return btn


func _make_new_farm_button() -> Button:
	var btn := Button.new()
	btn.name = "NewFarmButton"
	btn.text = "New Farm"
	btn.custom_minimum_size = Vector2(150, 40)
	btn.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	btn.add_theme_font_size_override("font_size", 15)
	_style_button(btn, Color(0.14, 0.30, 0.17), Color(0.55, 0.68, 0.52), Color(0.20, 0.38, 0.22))
	btn.pressed.connect(_open_confirm)
	return btn


func _make_start_button() -> Button:
	var btn := Button.new()
	btn.name = "StartButton"
	btn.text = "Start Farming"
	btn.custom_minimum_size = Vector2(CARD_W, 76)
	btn.add_theme_font_size_override("font_size", 28)
	_style_button(btn, Color(0.18, 0.42, 0.22), Color(1.0, 0.72, 0.15), Color(0.24, 0.52, 0.28))
	btn.pressed.connect(func(): start_game(false))
	return btn


# --- Credits (all builds; a licence obligation, not a nicety) -----------------

# Kept in one place and sourced from CREDITS.md, which is the provenance record.
# If an asset's licence changes, both must change together.
const CREDITS_TEXT := """Tiny Farm

Made with Godot Engine — MIT License
godotengine.org

MUSIC
"Wholesome" by Kevin MacLeod (incompetech.com)
Licensed under Creative Commons: By Attribution 4.0
creativecommons.org/licenses/by/4.0/

SOUND
Original effects synthesized for this project.
Harvest sounds by Valenspire (Freesound), CC0 1.0.

ART
Pixel art generated with Retro Diffusion
and post-processed for this project.

Full provenance for every asset is recorded in
CREDITS.md in the project repository."""


func _make_credits_button() -> Button:
	var btn := Button.new()
	btn.name = "CreditsButton"
	btn.text = "Credits"
	btn.custom_minimum_size = Vector2(110, 30)
	btn.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	btn.add_theme_font_size_override("font_size", 12)
	_style_button(btn, Color(0.12, 0.26, 0.15), Color(0.42, 0.55, 0.40), Color(0.17, 0.33, 0.20))
	btn.pressed.connect(_open_credits)
	return btn


func _open_credits() -> void:
	if _confirm_open:
		return
	_confirm_open = true  # also blocks tap-anywhere while the panel is up
	_set_attract_paused(true)

	_confirm_layer = Control.new()
	_confirm_layer.name = "CreditsLayer"
	_confirm_layer.set_anchors_preset(Control.PRESET_FULL_RECT)
	_confirm_layer.mouse_filter = Control.MOUSE_FILTER_STOP
	add_child(_confirm_layer)

	var dim := ColorRect.new()
	dim.set_anchors_preset(Control.PRESET_FULL_RECT)
	dim.color = Color(0.05, 0.09, 0.07, 1.0)
	dim.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_confirm_layer.add_child(dim)

	# Scrolled, because the text outgrows a phone screen in portrait and an
	# attribution nobody can reach is not an attribution.
	var scroll := ScrollContainer.new()
	scroll.set_anchors_preset(Control.PRESET_FULL_RECT)
	scroll.offset_left = 24
	scroll.offset_top = 16
	scroll.offset_right = -24
	scroll.offset_bottom = -60
	scroll.horizontal_scroll_mode = ScrollContainer.SCROLL_MODE_DISABLED
	_confirm_layer.add_child(scroll)

	var body := Label.new()
	body.text = CREDITS_TEXT
	body.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	body.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	body.add_theme_font_size_override("font_size", 14)
	body.add_theme_color_override("font_color", Color(0.90, 0.95, 0.88))
	body.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	scroll.add_child(body)

	var back := Button.new()
	back.name = "CreditsBackButton"
	back.text = "Back"
	back.custom_minimum_size = Vector2(150, 40)
	back.set_anchors_preset(Control.PRESET_CENTER_BOTTOM)
	back.anchor_left = 0.5
	back.anchor_right = 0.5
	back.offset_left = -75
	back.offset_top = -50
	back.offset_right = 75
	back.offset_bottom = -10
	back.add_theme_font_size_override("font_size", 16)
	_style_button(back, Color(0.18, 0.42, 0.22), Color(1.0, 0.72, 0.15), Color(0.24, 0.52, 0.28))
	back.pressed.connect(_close_confirm)
	_confirm_layer.add_child(back)

	back.grab_focus()


# --- Sound test (debug builds) ------------------------------------------------

func _make_sound_test_button() -> Button:
	var btn := Button.new()
	btn.name = "SoundTestButton"
	btn.text = "Sound Test"
	btn.custom_minimum_size = Vector2(130, 34)
	btn.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	btn.add_theme_font_size_override("font_size", 13)
	_style_button(btn, Color(0.13, 0.24, 0.30), Color(0.45, 0.62, 0.70), Color(0.18, 0.32, 0.40))
	btn.pressed.connect(_open_sound_test)
	return btn


func _open_sound_test() -> void:
	if _confirm_open:
		return
	_confirm_open = true  # also blocks tap-anywhere while the panel is up
	_set_attract_paused(true)

	_confirm_layer = Control.new()
	_confirm_layer.name = "SoundTestLayer"
	_confirm_layer.set_anchors_preset(Control.PRESET_FULL_RECT)
	_confirm_layer.mouse_filter = Control.MOUSE_FILTER_STOP
	add_child(_confirm_layer)

	var dim := ColorRect.new()
	dim.set_anchors_preset(Control.PRESET_FULL_RECT)
	dim.color = Color(0.05, 0.09, 0.07, 1.0)
	dim.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_confirm_layer.add_child(dim)

	# The list outgrew a fixed-height box, which left the last entries off screen
	# with no way to reach them on a tablet. Scroll it instead.
	var scroll := ScrollContainer.new()
	scroll.set_anchors_preset(Control.PRESET_FULL_RECT)
	scroll.offset_left = 20
	scroll.offset_top = 16
	scroll.offset_right = -20
	scroll.offset_bottom = -16
	scroll.horizontal_scroll_mode = ScrollContainer.SCROLL_MODE_DISABLED
	_confirm_layer.add_child(scroll)

	var box := VBoxContainer.new()
	box.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	box.alignment = BoxContainer.ALIGNMENT_CENTER
	box.add_theme_constant_override("separation", 8)
	scroll.add_child(box)

	var head := Label.new()
	head.text = "Sound Test"
	head.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	head.add_theme_font_size_override("font_size", 26)
	head.add_theme_color_override("font_color", Color(1.0, 0.86, 0.45))
	box.add_child(head)

	var hint := Label.new()
	hint.text = "Tap a sound to hear it."
	hint.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	hint.add_theme_font_size_override("font_size", 13)
	hint.add_theme_color_override("font_color", Color(0.78, 0.86, 0.76))
	box.add_child(hint)

	var grid := GridContainer.new()
	grid.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	grid.columns = 2
	grid.add_theme_constant_override("h_separation", 8)
	grid.add_theme_constant_override("v_separation", 8)
	box.add_child(grid)

	# Driven off AudioManager's own table so this list cannot drift from the game.
	var names: Array = AudioManager.sfx_streams.keys()
	names.sort()
	for n in names:
		var b := Button.new()
		b.text = String(n)
		b.custom_minimum_size = Vector2(184, 42)
		b.add_theme_font_size_override("font_size", 16)
		_style_button(b, Color(0.16, 0.34, 0.20), Color(0.62, 0.76, 0.58), Color(0.22, 0.44, 0.26))
		b.pressed.connect(func(): AudioManager.play_sfx(String(n)))
		grid.add_child(b)

	# Candidate takes, played straight off disk so the game's own table stays
	# clean. Listed explicitly rather than by scanning res://, which is not
	# reliable for imported assets inside an exported build.
	if not SFX_CANDIDATES.is_empty():
		var cand_player := AudioStreamPlayer.new()
		_confirm_layer.add_child(cand_player)
		var sep := Label.new()
		sep.text = "candidates (A/B against the above)"
		sep.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
		sep.add_theme_font_size_override("font_size", 12)
		sep.add_theme_color_override("font_color", Color(0.70, 0.80, 0.86))
		box.add_child(sep)

		var cgrid := GridContainer.new()
		cgrid.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
		cgrid.columns = 2
		cgrid.add_theme_constant_override("h_separation", 8)
		cgrid.add_theme_constant_override("v_separation", 8)
		box.add_child(cgrid)

		for cand in SFX_CANDIDATES:
			var cb := Button.new()
			cb.text = String(cand)
			cb.custom_minimum_size = Vector2(184, 40)
			cb.add_theme_font_size_override("font_size", 15)
			_style_button(cb, Color(0.13, 0.24, 0.30), Color(0.45, 0.62, 0.70), Color(0.18, 0.32, 0.40))
			cb.pressed.connect(func():
				var stream = load("res://assets/audio/sfx/%s.wav" % cand)
				if stream != null:
					cand_player.stream = stream
					cand_player.play())
			cgrid.add_child(cb)

	var music := Button.new()
	music.name = "MusicToggle"
	music.text = "Music: on"
	music.custom_minimum_size = Vector2(184, 36)
	music.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	music.add_theme_font_size_override("font_size", 14)
	_style_button(music, Color(0.13, 0.24, 0.30), Color(0.45, 0.62, 0.70), Color(0.18, 0.32, 0.40))
	music.pressed.connect(func():
		# Mute the bed so a short SFX can be judged on its own.
		var p: AudioStreamPlayer = AudioManager.bgm_player
		if p == null:
			return
		if p.playing:
			p.stop()
			music.text = "Music: off"
		else:
			p.play()
			music.text = "Music: on")
	box.add_child(music)

	var back := Button.new()
	back.name = "SoundTestBackButton"
	back.text = "Back"
	back.custom_minimum_size = Vector2(150, 40)
	back.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	back.add_theme_font_size_override("font_size", 16)
	_style_button(back, Color(0.18, 0.42, 0.22), Color(1.0, 0.72, 0.15), Color(0.24, 0.52, 0.28))
	back.pressed.connect(_close_confirm)
	box.add_child(back)

	back.grab_focus()


# --- The zoo (debug builds) ---------------------------------------------------
#
# T-33, the designer 2026-09-01: *"Some sort of way for us to experience the new
# entities in the game... a 'zoo' of the entities we've created, and a way to
# select or add them in a useful way just to see them doing their thing."*
#
# The whole bestiary ships behind `PER_DAY := 0`, so nobody has ever seen a rabbit
# outside a test's assertions. This is that door, and it is deliberately the Sound
# Test's own door — same gate, same row, same corner — because there is one
# place in this game where things go to be looked at.
#
# It changes scene rather than opening a panel: the zoo is a second farm with a
# clock of its own, and the attract loop is already running one behind this menu.

func _make_zoo_button() -> Button:
	var btn := Button.new()
	btn.name = "ZooButton"
	btn.text = "Zoo"
	btn.custom_minimum_size = Vector2(130, 34)
	btn.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	btn.add_theme_font_size_override("font_size", 13)
	_style_button(btn, Color(0.13, 0.24, 0.30), Color(0.45, 0.62, 0.70), Color(0.18, 0.32, 0.40))
	btn.pressed.connect(_open_zoo)
	return btn


func _open_zoo() -> void:
	if _confirm_open:
		return
	InputManager.has_click = false
	AudioManager.play_sfx("click")
	get_tree().change_scene_to_file("res://ui/zoo_screen.tscn")


# T-37: the home, a scene-changing door on the Zoo's pattern.
func _make_home_button() -> Button:
	var btn := Button.new()
	btn.name = "HomeButton"
	btn.text = "Home"
	btn.custom_minimum_size = Vector2(130, 34)
	btn.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	btn.add_theme_font_size_override("font_size", 13)
	_style_button(btn, Color(0.24, 0.18, 0.13), Color(0.70, 0.55, 0.40), Color(0.32, 0.24, 0.18))
	btn.pressed.connect(_open_home)
	return btn


func _open_home() -> void:
	if _confirm_open:
		return
	InputManager.has_click = false
	AudioManager.play_sfx("click")
	get_tree().change_scene_to_file("res://ui/home_screen.tscn")


# --- New Farm confirmation ----------------------------------------------------

func _open_confirm() -> void:
	if _confirm_open:
		return
	_confirm_open = true
	_set_attract_paused(true)  # one moving thing at a time

	_confirm_layer = Control.new()
	_confirm_layer.name = "ConfirmLayer"
	_confirm_layer.set_anchors_preset(Control.PRESET_FULL_RECT)
	_confirm_layer.mouse_filter = Control.MOUSE_FILTER_STOP  # swallow taps behind it
	add_child(_confirm_layer)

	var dim := ColorRect.new()
	dim.set_anchors_preset(Control.PRESET_FULL_RECT)
	dim.color = Color(0, 0, 0, 0.72)
	dim.mouse_filter = Control.MOUSE_FILTER_IGNORE
	_confirm_layer.add_child(dim)

	# Solid card behind the prompt: dimming alone left the Continue card bleeding
	# through the words, which is the last place we want a legibility problem.
	var backing := Panel.new()
	backing.set_anchors_preset(Control.PRESET_CENTER)
	backing.anchor_left = 0.5
	backing.anchor_top = 0.5
	backing.anchor_right = 0.5
	backing.anchor_bottom = 0.5
	backing.offset_left = -190
	backing.offset_top = -100
	backing.offset_right = 190
	backing.offset_bottom = 100
	backing.mouse_filter = Control.MOUSE_FILTER_IGNORE
	var backing_style := StyleBoxFlat.new()
	backing_style.bg_color = Color(0.09, 0.16, 0.11, 0.98)
	backing_style.border_color = Color(0.55, 0.68, 0.52)
	backing_style.set_border_width_all(2)
	backing_style.set_corner_radius_all(12)
	backing.add_theme_stylebox_override("panel", backing_style)
	_confirm_layer.add_child(backing)

	var box := VBoxContainer.new()
	box.set_anchors_preset(Control.PRESET_CENTER)
	box.anchor_left = 0.5
	box.anchor_top = 0.5
	box.anchor_right = 0.5
	box.anchor_bottom = 0.5
	box.offset_left = -170
	box.offset_top = -80
	box.offset_right = 170
	box.offset_bottom = 80
	box.add_theme_constant_override("separation", 10)
	_confirm_layer.add_child(box)

	var warn := Label.new()
	warn.text = "Start a new farm?"
	warn.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	warn.add_theme_font_size_override("font_size", 24)
	warn.add_theme_color_override("font_color", Color.WHITE)
	box.add_child(warn)

	var detail := Label.new()
	detail.text = "Your Day %d farm will be replaced." % _summary.get("day", 1)
	detail.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	detail.add_theme_font_size_override("font_size", 14)
	detail.add_theme_color_override("font_color", Color(0.92, 0.86, 0.72))
	box.add_child(detail)

	var keep := Button.new()
	keep.name = "KeepFarmButton"
	keep.text = "Keep my farm"
	keep.custom_minimum_size = Vector2(220, 46)
	keep.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	keep.add_theme_font_size_override("font_size", 18)
	_style_button(keep, Color(0.18, 0.42, 0.22), Color(1.0, 0.72, 0.15), Color(0.24, 0.52, 0.28))
	keep.pressed.connect(_close_confirm)
	box.add_child(keep)

	var wipe := Button.new()
	wipe.name = "ConfirmNewFarmButton"
	wipe.text = "Yes, start over"
	wipe.custom_minimum_size = Vector2(180, 36)
	wipe.size_flags_horizontal = Control.SIZE_SHRINK_CENTER
	wipe.add_theme_font_size_override("font_size", 14)
	_style_button(wipe, Color(0.38, 0.18, 0.14), Color(0.72, 0.42, 0.34), Color(0.46, 0.22, 0.17))
	wipe.pressed.connect(_on_new_farm)
	box.add_child(wipe)

	keep.grab_focus()  # the safe option is the default


func _close_confirm() -> void:
	_confirm_open = false
	_set_attract_paused(false)
	if _confirm_layer:
		_confirm_layer.queue_free()
		_confirm_layer = null


func _gui_input(event: InputEvent) -> void:
	# Tap-anywhere still resumes the farm (the kid-friendly default from Q-8's
	# ruling), but never while the confirmation is up.
	if _confirm_open or not _has_save:
		return
	if event is InputEventMouseButton and event.pressed and event.button_index == MOUSE_BUTTON_LEFT:
		accept_event()
		start_game(true)
	elif event is InputEventScreenTouch and event.pressed:
		accept_event()
		start_game(true)
	elif event.is_action_pressed("ui_accept"):
		accept_event()
		start_game(true)


func _on_new_farm() -> void:
	# Park the current farm first: with a single save slot, an accidental New
	# Farm would otherwise destroy it at the first sleep. Recoverable by
	# renaming the .bak files back.
	if _has_save:
		DirAccess.copy_absolute(GameState.save_path, GameState.save_path + ".bak")
		if FileAccess.file_exists(GameState.replay_path):
			DirAccess.copy_absolute(GameState.replay_path, GameState.replay_path + ".bak")
	start_game(false)


func start_game(load_save: bool) -> void:
	print("Starting game... (continue=%s)" % load_save)
	GameState.pending_load = load_save
	if not load_save:
		GameState.reset()
	InputManager.has_click = false
	AudioManager.play_sfx("click")
	var err = get_tree().change_scene_to_file("res://main.tscn")
	if err != OK:
		print("Failed to change scene! Error code: ", err)
